[tool.poetry]
name = "django-openid"
version = "0.1.0"
description = ""
authors = ["ellaverak <ella.korkeaaho@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
