# Generated by Django 4.2.8 on 2023-12-10 17:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openid', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=django_cryptography.fields.encrypt(models.CharField(default='000000000')),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
